In [1]:
# Reading Data from differennt sources

import pandas as pd

from io import StringIO # StringIO is used to read data from a string as if it were a file

Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df = pd.read_json(StringIO(Data))
print(df)

  employee_name            email  \
0         James  james@gmail.com

                                         job_profile
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [ ]:
df.to_json() # Convert DataFrame to JSON string

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [ ]:
df.to_json(orient='index') # Convert DataFrame to JSON string with index orientation

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [4]:
df.to_json(orient='records') # Convert DataFrame to JSON string with records orientation

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [6]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None) # Read CSV data from a URL and create a DataFrame
print(df.head()) # Print the first 5 rows of the DataFrame

   0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93

     13
0  1065
1  1050
2  1185
3  1480
4   735

In [7]:
df.to_csv("wine.csv") # Save the DataFrame to a CSV file named "wine.csv" in the current working directory

In [ ]:
!pip install lxml # Install the lxml library, which is required for parsing XML data

Collecting lxml
  Downloading lxml-6.0.2-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.6 kB)
Downloading lxml-6.0.2-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 3.4 MB/s  0:00:01m0:00:0100:01
Installing collected packages: lxml
Successfully installed lxml-6.0.2

In [ ]:
!pip install html5lib # Install the html5lib library, which is required for parsing HTML data
!pip install beautifulsoup4 # Install the beautifulsoup4 library, which is used for parsing HTML and XML data

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in /home/prateek/da_bootcamp/python/venv/lib/python3.12/site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /home/prateek/da_bootcamp/python/venv/lib/python3.12/site-packages (from html5lib) (0.5.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1
Requirement already satisfied: beautifulsoup4 in /home/prateek/da_bootcamp/python/venv/lib/python3.12/site-packages (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in /home/prateek/da_bootcamp/python/venv/lib/python3.12/site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/prateek/da_bootcamp/python/venv/lib/python3.12/site-packages (from beautifulsoup4) (4.15.0)

In [11]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df=pd.read_html(url)

In [14]:
df[0] # The read_html function returns a list of DataFrames, so we access the first DataFrame using df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [20]:
!pip install openpyxl # Install the openpyxl library, which is required for reading Excel files

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [ ]:
df_excel=pd.read_excel('data.xlsx') # Read an Excel file named "data.xlsx" from the current working directory and create a DataFrame

In [ ]:
df_excel.to_pickle('df_excel') # Save the DataFrame to a pickle file named "df_excel" in the current working directory

In [23]:
pd.read_pickle('df_excel') # Read the DataFrame from the pickle file named "df_excel" in the current working directory

           Date Region Product  Units_Sold   Revenue     Cost   Profit
0    2024-01-01   West       C         101   6062.53  3824.20  2238.33
1    2024-01-02   East       B         174   5632.37  3931.82  1700.55
2    2024-01-03   West       D          61   2150.73  1322.83   827.90
3    2024-01-04   East       D          14   1117.51   868.28   249.24
4    2024-01-05   East       C          20   1627.68  1272.14   355.54
..          ...    ...     ...         ...       ...      ...      ...
195  2024-07-14  North       A         142  10331.69  8172.02  2159.67
196  2024-07-15   West       C         195  10911.99  7900.14  3011.85
197  2024-07-16  North       C          71   5714.07  3290.41  2423.66
198  2024-07-17  North       C          58   3635.35  2025.15  1610.21
199  2024-07-18   West       B          98   2860.23  1824.32  1035.91

[200 rows x 7 columns]